MAX_KEY_CAPACITY: int = 32
MAX_VALUE_SIZE: int = 16 * 1024  # KB -> B
MAX_DATA_STORE_SIZE: int = 1 * 1024 * 1024 * 1024  # GB -> B
DATA_STORE_FILE_NAME: str = "DATA_STORE.json"


def get_MAX_KEY_CAPACITY():
    return MAX_KEY_CAPACITY


def get_MAX_VALUE_SIZE():
    return MAX_VALUE_SIZE


def get_MAX_DATA_STORE_SIZE():
    return MAX_DATA_STORE_SIZE


def get_DATA_STORE_FILE_NAME():
    return DATA_STORE_FILE_NAME
